#!/bin/bash
# Check if app is running on starting X

list=(dropbox highlights mpd mpdscribble xautolock)  

for app in "${list[@]}"; do
    check=$(ps -C "$app" -opid=)
    if [[ -z "$check" ]]; then
        case "$app" in
            dropbox) /usr/bin/dropboxd &
                    ;;
         highlights) $HOME/Scripts/highlights & 
                    ;;
                mpd) mpd $HOME/.mpd/mpd.conf 
                    ;;
        mpdscribble) mpdscribble & 
                    ;;
          xautolock) xautolock -time 8 -locker "i3lock -c 302B54" \
                     -nowlocker "i3lock -c 302B54" &
                    ;;
        esac
    fi
done

