#!/bin/bash

RXB=$(cat /sys/class/net/eth0/statistics/rx_bytes)
TXB=$(cat /sys/class/net/eth0/statistics/tx_bytes)
sleep 2 
RXBN=$(cat /sys/class/net/eth0/statistics/rx_bytes)
TXBN=$(cat /sys/class/net/eth0/statistics/tx_bytes)
RXDIF=$(echo $((RXBN - RXB)) )
TXDIF=$(echo $((TXBN - TXB)) )
RXT=$(ifconfig eth0 | grep -i "RX Bytes:" | awk '{print $2}' | cut -d: -f2)
TXT=$(ifconfig eth0 | grep -i "RX Bytes:" | awk '{print $6}' | cut -d: -f2)

echo -e "\b\x04$((RXDIF / 1024 / 2))K/s \x06$((TXDIF / 1024 / 2))K/s\x01"
