#!/usr/bin/env bash
# email reminder notes using at(1)...

usage() {
    cat <<EOF
  Options:

  -l     | list current jobs
  -p n   | print details for job n
  -h     | print this message

EOF
}

print() {
    awk -F\" '/gmail/ { print $2 }' <(at -c "$@")
}

list() {
    atq | sort -r -k3M -k4
}

if [[ $# -ge 1 ]]; then
    case "$1" in
        -p) print "$2" && exit 0 ;;
        -l) list && exit 0 ;;
        -h) usage && exit 0 ;;
    esac
fi

read -p "Time of message? [HH:MM] " time
read -p "Date of message? [dd.mm.yy] " date
read -p "Message body? " message

at "$time" "$date" << EOF
echo "$message" | mutt -s "REMINDER" jasonwryan@gmail.com
EOF

