#!/usr/bin/env bash
# Unlock encrypted partitions at boot

stty -echo
read -p "Enter password for the volume: " password
stty echo

printf "\n%s\n" "Connecting…"

ssh -vvv -o UserKnownHostsFile=~/.ssh/known_hosts.reboot \
    -i .ssh/reboot_rsa root@192.168.1.200 -p 22 \
    "echo -ne \""$password"\" >/lib/cryptsetup/passfifo"

